steps:
  # Build Docker image for main app
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_IMAGE}
      - .
    id: build-main-app

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_IMAGE}
      - --region
      - ${_REGION}
      - --allow-unauthenticated
      - --set-env-vars
      - NODE_ENV=production,CHATBOT_BASE_URL=${_CHATBOT_BASE_URL}
      - --set-secrets
      - DATABASE_URL=DATABASE_URL:latest,VITE_SUPABASE_URL=VITE_SUPABASE_URL:latest,VITE_SUPABASE_ANON_KEY=VITE_SUPABASE_ANON_KEY:latest,SLACK_WEBHOOK_URL=SLACK_WEBHOOK_URL:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_CALLBACK_URL=GOOGLE_CALLBACK_URL:latest,ALLOWED_ADMIN_EMAILS=ALLOWED_ADMIN_EMAILS:latest
    id: deploy-main-app

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY

